version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_TOKEN: "your_api_token"
        OPEN_AI_API_KEY: "your_open_ai_api_key"
        OPEN_AI_BASE_URL: "https://api.moonshot.cn/v1"
    ports:
      - "5001:5001"